CREATE TABLE `Mem_Member` (
  `id` INT(11)  NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(20)  DEFAULT NULL  COMMENT '名字',
  `age` TINYINT(3)  DEFAULT NULL  COMMENT '年龄',
  `level_id` BIGINT(20)  DEFAULT NULL  COMMENT '等级',
  `phone` VARCHAR(20)  DEFAULT NULL  COMMENT '手机',
  `email` VARCHAR(50)  DEFAULT NULL  COMMENT '邮箱',
  `birthDay` DATE  DEFAULT NULL  COMMENT '生日',
  `point` DECIMAL(19,5)  DEFAULT NULL  COMMENT '积分余额',
  `isDelete` TINYINT(1)  DEFAULT NULL  COMMENT '是否已删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='会员';